language: node_js
node_js:
  - "6"
services:
  - mongodb
cache:
  directories:
    - node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: BetterJump/Matt-Service-RelatedItems
    bucket: better-jump-service
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: better-jump-service
    key: latest.zip
    bundle_type: zip
    application: betterjumpservice
    deployment_group: betterjumpservice
    region: us-east-1
    on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
